# Generated by Django 2.2.2 on 2021-02-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '旅游分类',
                'verbose_name_plural': '旅游分类',
                'db_table': 'category',
            },
        ),
    ]
