# Generated by Django 2.2.2 on 2021-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='tag',
            new_name='category',
        ),
    ]
