# Generated by Django 2.2.2 on 2021-02-19 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210218_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='区域')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='假期名称')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='旅游线路地点')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeId', models.BigIntegerField(verbose_name='线路编号')),
                ('visa', models.CharField(blank=True, max_length=255, null=True, verbose_name='签证')),
                ('heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='头标题')),
                ('mheading', models.CharField(max_length=255, null=True, verbose_name='二级头标题')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('status', models.SmallIntegerField(choices=[(0, '上线'), (1, '下线')], default=0, verbose_name='线路状态')),
                ('desc', models.TextField(verbose_name='描述')),
                ('cover', models.ImageField(blank=True, help_text='图片长宽固定的', null=True, upload_to='banner/cover/', verbose_name='上传封面图片')),
                ('map', models.FileField(blank=True, help_text='图片长宽固定的', null=True, upload_to='banner/map/', verbose_name='上传路线图片')),
                ('routeSort', models.IntegerField(verbose_name='线路排序')),
                ('duration', models.SmallIntegerField(default=0, verbose_name='周期')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.Category', verbose_name='分类')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Area', verbose_name='目的地')),
                ('overview', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='travel.Overview', verbose_name='线路地点')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Country'),
        ),
    ]
