# Generated by Django 2.2.2 on 2021-02-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20210219_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '旅游分类轮播图', 'verbose_name_plural': '旅游分类轮播图'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家', 'verbose_name_plural': '国家'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': '假期表', 'verbose_name_plural': '假期表'},
        ),
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name': '具体路线地点图', 'verbose_name_plural': '具体路线地点图'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': '路线', 'verbose_name_plural': '路线'},
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='holiday',
        ),
        migrations.AlterModelTable(
            name='overview',
            table='overview',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
    ]
