# Generated by Django 2.2.2 on 2021-02-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20210219_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='mheading',
        ),
        migrations.RemoveField(
            model_name='route',
            name='overview',
        ),
        migrations.AddField(
            model_name='route',
            name='overview',
            field=models.ManyToManyField(to='travel.Overview', verbose_name='线路地点'),
        ),
    ]
