# Generated by Django 2.2.2 on 2021-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210219_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='聚合标签')),
            ],
            options={
                'verbose_name': '聚合标签',
                'verbose_name_plural': '聚合标签',
                'db_table': 'focus_tag',
            },
        ),
        migrations.RemoveField(
            model_name='route',
            name='sort_num',
        ),
        migrations.AlterField(
            model_name='route',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一级标题'),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(max_length=255, verbose_name='二级标题'),
        ),
        migrations.AddField(
            model_name='route',
            name='focus_tag',
            field=models.ManyToManyField(to='travel.FocusTag', verbose_name='聚合标签'),
        ),
    ]
