# Generated by Django 2.2.2 on 2021-02-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_route_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='strength',
            field=models.IntegerField(default=0, verbose_name='体能系数'),
        ),
    ]
