# Generated by Django 2.2.2 on 2021-02-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20210220_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='travel.Area', verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='route',
            name='focus_tag',
            field=models.ManyToManyField(null=True, to='travel.FocusTag', verbose_name='聚合标签'),
        ),
        migrations.AlterField(
            model_name='route',
            name='overview',
            field=models.ManyToManyField(null=True, to='travel.Overview', verbose_name='线路地点'),
        ),
    ]
