# Generated by Django 2.2.2 on 2021-02-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20210220_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.Area', verbose_name='目的地'),
        ),
    ]
