# Generated by Django 2.2.2 on 2021-01-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotbanner',
            options={'verbose_name': '热门景点轮播图', 'verbose_name_plural': '热门景点轮播图'},
        ),
    ]
