# Generated by Django 2.2.2 on 2021-01-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_tagbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '轮播图分类', 'verbose_name_plural': '轮播图分类'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='hahaha_tag',
        ),
    ]
