# Generated by Django 2.2.2 on 2021-02-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210117_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '分类轮播图标签', 'verbose_name_plural': '分类轮播图标签'},
        ),
    ]
