# Generated by Django 2.2.2 on 2021-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210220_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbanner',
            name='link',
            field=models.CharField(blank=True, help_text='链接', max_length=128, null=True, verbose_name='链接'),
        ),
    ]
